-- Add profile fields to users table
ALTER TABLE users ADD COLUMN email VARCHAR(200) DEFAULT NULL;
ALTER TABLE users ADD COLUMN display_name VARCHAR(100) DEFAULT NULL;
ALTER TABLE users ADD COLUMN font VARCHAR(100) DEFAULT NULL;
