ALTER TABLE vacation_days ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'approved';
ALTER TABLE vacation_days ADD COLUMN requested_by VARCHAR(100) DEFAULT NULL;
ALTER TABLE vacation_days ADD COLUMN approved_by VARCHAR(100) DEFAULT NULL;
ALTER TABLE vacation_days ADD COLUMN approved_at TIMESTAMP NULL DEFAULT NULL;
